DROP DATABASE IF EXISTS BDD_gestion_ressources_universitaires;
CREATE DATABASE BDD_gestion_ressources_universitaires;
USE BDD_gestion_ressources_universitaires;

CREATE TABLE UTILISATEUR( 
USERNAME VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(100),
NOM_USER VARCHAR(100),
PRENOM_USER VARCHAR(100),
TYPE_USER ENUM('ENSEIGNANT','ETUDIANT','TECHNICIEN','ADMINISTRATIF'),
PRIMARY KEY (USERNAME));


CREATE TABLE MESSAGE( 
ID_MESSAGE INT NOT NULL AUTO_INCREMENT,
CONTENU_MESSAGE VARCHAR(2048),
PRIMARY KEY (ID_MESSAGE));

CREATE TABLE DISCUSSION(
 ID_DISCUSSION INT NOT NULL AUTO_INCREMENT,
 TITRE_DISCUSSION VARCHAR(100),
 PRIMARY KEY (ID_DISCUSSION));
 
CREATE TABLE GROUPE( 
ID_GROUPE INT NOT NULL AUTO_INCREMENT,
NOM_GROUPE VARCHAR(100),
PRIMARY KEY (ID_GROUPE));

CREATE TABLE APPARTENIR(
ID_GROUPE INT NOT NULL,
USERNAME VARCHAR(100) NOT NULL,
PRIMARY KEY (ID_GROUPE,USERNAME),
FOREIGN KEY (ID_GROUPE) REFERENCES GROUPE(ID_GROUPE),
FOREIGN KEY (USERNAME) REFERENCES UTILISATEUR(USERNAME));

CREATE TABLE ENVOYER( 
USERNAME VARCHAR(100) NOT NULL, 
ID_MESSAGE INT NOT NULL, 
DATE_ENVOI_MESSAGE DATETIME, 
PRIMARY KEY (USERNAME,ID_MESSAGE), 
FOREIGN KEY (USERNAME) REFERENCES UTILISATEUR(USERNAME), 
FOREIGN KEY (ID_MESSAGE) REFERENCES MESSAGE(ID_MESSAGE));

CREATE TABLE CONTIENT( 
ID_DISCUSSION INT NOT NULL, 
ID_MESSAGE INT NOT NULL, 
PRIMARY KEY (ID_DISCUSSION,ID_MESSAGE),
FOREIGN KEY (ID_MESSAGE) REFERENCES MESSAGE(ID_MESSAGE),
FOREIGN KEY (ID_DISCUSSION) REFERENCES DISCUSSION(ID_DISCUSSION));

CREATE TABLE CREER( 
ID_DISCUSSION INT NOT NULL,
USERNAME VARCHAR(100) NOT NULL,
PRIMARY KEY (ID_DISCUSSION,USERNAME), 
FOREIGN KEY (ID_DISCUSSION) REFERENCES DISCUSSION(ID_DISCUSSION), 
FOREIGN KEY (USERNAME) REFERENCES UTILISATEUR(USERNAME));

